### ISSUE TITLE
A repo by an other name would shadow less.

### ISSUE THREAD

**Issue by danielballan** [Nikea/scikit-xray-examples#10]
Yesterday I had the opinion that we should leave this called "Demos," but I have changed by mind. It might be better manners to name this something more specific the project -- scikit-xray-examples or xray-examples.

**Comment by danielballan** [comment]
@giltis Any opinion on this?

**Comment by sameera2004** [comment]
I like the name scikit-xray-examples too.

**Comment by licode** [comment]
I like `scikit-xray-examples`

**Comment by celiafish** [comment]
I agree.

Wei

**Comment by ericdill** [comment]
Renamed repo, so closing this issue
