### ISSUE TITLE
Reorganize demos

### ISSUE THREAD

**Issue by ericdill** [Nikea/scikit-xray-examples#23]
Reorganize the demos so that they are organized by scientific use case (1-time, calibration, etc.), not by demo type (script, vistrails, ipynb). 

Such a reorganization has the advantage of being able to include a science-specific readme in these folders. See [the dpc demo] (https://github.com/Nikea/scikit-xray-examples/tree/master/demos/dpc) for a concrete version of what I mean.

**Comment by danielballan** [comment]
I approve this message.

**Comment by tacaswell** [comment]
:+1:
